# Spring Boot Server Config
#server:
#  port: 8090
#  address: localhost

# CXF Context Root
#cxf:
#  path: /jpa

# H2 Web Console (H2ConsoleProperties)
spring:
  main.sources: com.was.spring.cxf.repository.CustomerRepository, com.was.spring.cxf.impl.CustomerServiceImpl, com.was.spring.cxf.impl.HelloServiceImpl 
  h2:
    console:
      enabled: false # Enable the console.
      path: /h2-console # Path at which the console will be available.
      settings:
        trace: false # Enable trace output.
        web-allow-others: false # Enable remote access.
  jpa:
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
